package com.zaphira.transaction.model.enums;

public enum TransactionType {
    P2P_TRANSFER,
    INTERNAL_TRANSFER,
    CROSS_BORDER_TRANSFER,
    BULK_TRANSFER,
    SPLIT_TRANSFER,
    GROUP_TRANSFER,
    MERCHANT_PAYMENT,
    BILL_PAYMENT,
    SUBSCRIPTION_PAYMENT,
    INVOICE_PAYMENT,
    QR_PAYMENT,
    PAYMENT_LINK,
    IN_APP_PAYMENT,
    CONTACTLESS_PAYMENT,
    MOBILE_RECHARGE,
    WALLET_TOPUP,
    TRANSIT_TOPUP,
    GIFT_CARD_PURCHASE,
    ATM_WITHDRAWAL,
    AGENT_WITHDRAWAL,
    BANK_TRANSFER,
    CARD_TRANSFER,
    CRYPTO_WITHDRAWAL,
    ESCROW,
    SCHEDULED,
    RECURRING,
    SPLIT_BILL,
    REQUEST_MONEY,
    DONATION,
    TIP,
    REFUND,
    REVERSAL
}


