
otp:
  ttl-minutes: 10
  max-tokens-per-user: 5  # Limite le nombre de tokens actifs par utilisateur
  cleanup:
    enabled: true
    interval-minutes: 5    # Nettoyage toutes les 5 minutes
    deep-cleanup-hours: 1  # Nettoyage profond toutes les heures

server:
  port: 8089

spring:
  # PostgreSQL configuration (same as user-service)
  datasource:
    url: jdbc:postgresql://192.168.0.122:5432/wallet_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

