server:
  port: 8085

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: 192.168.0.122:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

telegram:
  bot:
    token: 7490034483:AAFCwqBCCjpaHGfLlsfz6ucymsTaU0peov4
    chat-id: 7584204126

logging:
  level:
    com.zaphira.notification: DEBUG

