-- ============================================================================
-- DIRECT SQL IMPLEMENTATION - validation_requests Table
-- ============================================================================
-- Database: wallet_db
-- User: postgres
-- Host: 192.168.0.122
-- Port: 5432
-- ============================================================================
-- EXECUTION: psql -h 192.168.0.122 -U postgres -d wallet_db -f this_file.sql
-- ============================================================================

-- Step 1: Create the table
-- ============================================================================

CREATE TABLE IF NOT EXISTS validation_requests (
    id BIGSERIAL PRIMARY KEY,
    
    correlation_id VARCHAR(36) NOT NULL UNIQUE,
    transaction_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    expires_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '5 minutes'),
    
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Step 2: Create indexes for performance
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_validation_requests_correlation_id 
    ON validation_requests(correlation_id);

CREATE INDEX IF NOT EXISTS idx_validation_requests_transaction_id 
    ON validation_requests(transaction_id);

CREATE INDEX IF NOT EXISTS idx_validation_requests_status 
    ON validation_requests(status);

CREATE INDEX IF NOT EXISTS idx_validation_requests_expires_at 
    ON validation_requests(expires_at);

CREATE INDEX IF NOT EXISTS idx_validation_requests_pending 
    ON validation_requests(status, expires_at) 
    WHERE status = 'PENDING';

-- Step 3: Add documentation comments
-- ============================================================================

COMMENT ON TABLE validation_requests IS 
    'Tracks validation requests for Kafka idempotence. Ensures exactly-once processing of validation results.';

COMMENT ON COLUMN validation_requests.id IS 
    'Auto-incremented primary key for internal database use.';

COMMENT ON COLUMN validation_requests.correlation_id IS 
    'Unique UUID generated by transaction-service. Used to detect and prevent duplicate message processing (idempotence key).';

COMMENT ON COLUMN validation_requests.transaction_id IS 
    'Foreign key reference to the transaction being validated.';

COMMENT ON COLUMN validation_requests.status IS 
    'Processing status: PENDING (awaiting validation result), PROCESSED (result received and handled), EXPIRED (no response within 5 minutes).';

COMMENT ON COLUMN validation_requests.requested_at IS 
    'Timestamp when the validation request was created.';

COMMENT ON COLUMN validation_requests.processed_at IS 
    'Timestamp when the validation result was received and processed. NULL until status becomes PROCESSED.';

COMMENT ON COLUMN validation_requests.expires_at IS 
    'Timestamp after which the validation is considered expired (default: 5 minutes). Used for timeout detection and cleanup.';

COMMENT ON COLUMN validation_requests.created_at IS 
    'Audit: Timestamp when the database row was created.';

COMMENT ON COLUMN validation_requests.updated_at IS 
    'Audit: Timestamp of the last update to the database row.';

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Verify table created
SELECT 
    table_name,
    table_type
FROM information_schema.tables
WHERE table_schema = 'public' 
  AND table_name = 'validation_requests';

-- Verify columns
SELECT 
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'validation_requests'
ORDER BY ordinal_position;

-- Verify indexes
SELECT 
    indexname,
    tablename,
    indexdef
FROM pg_indexes
WHERE tablename = 'validation_requests'
ORDER BY indexname;

-- Verify table is empty and ready
SELECT COUNT(*) as row_count FROM validation_requests;

-- ============================================================================
-- SUCCESS MESSAGE
-- ============================================================================
-- If you see above:
-- ✅ table_name = validation_requests
-- ✅ 9 columns listed
-- ✅ 5 indexes listed
-- ✅ row_count = 0
-- Then the migration is SUCCESSFUL!
-- ============================================================================
