spring.application.name=transaction-service
server.port=8083

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://192.168.0.122:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ✅ JWT Configuration
app.jwt.secret=7pBJFFNs9RzeTwTz/NHFY1e1QyFVnDoZbBTG8zsdGHeAsAzmqcxLneWASllVgTbAdgdrS+XhAR9nfg1hPglA3Q==
app.jwt.access-expiration=900000
# 15s
app.jwt.refresh-expiration=2592000000    
# 30 days

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

# Wallet service integration
wallet.service.base-url=
wallet.service.wallet-details-path=/api/wallets/{walletNumber}
wallet.service.transfer-path=/api/wallets/transfer
wallet.service.timeout-ms=5000

# Transaction limits & authorization
transaction.limits.per-transaction=5000
transaction.limits.daily=20000
transaction.limits.weekly=50000
transaction.limits.monthly=150000
transaction.limits.authorization-threshold=1000
transaction.limits.authorization.expiry=PT5M
transaction.limits.authorization.default-mode=OTP
transaction.limits.authorization.expose-challenge-in-response=true

# Fees
transaction.fees.fixed=0
transaction.fees.percentage=0.005
transaction.fees.max=2000
transaction.fees.currency=XOF

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
