spring.application.name=zaphira
server.port=8081

# PostgreSQL configuration
# Point to the central DB host used in the environment
spring.datasource.url=jdbc:postgresql://192.168.0.122:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ✅ JWT Configuration
app.jwt.secret=7pBJFFNs9RzeTwTz/NHFY1e1QyFVnDoZbBTG8zsdGHeAsAzmqcxLneWASllVgTbAdgdrS+XhAR9nfg1hPglA3Q==
app.jwt.access-expiration=100000
# 15s
app.jwt.refresh-expiration=2592000000
# 30 days

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
