server:
  port: 8086

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://192.168.0.122:5432/wallet_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: 192.168.0.122:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      connections.max.idle.ms: 180000
      retry.backoff.ms: 100
  
  lifecycle:
    timeout-per-shutdown-phase: 30s

# Ajouter cette section
kafka:
  topics:
    user-created: user-created-topic
    wallet-created: wallet-created-topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/