-- Migration: Create validation_requests table for Kafka idempotence tracking
-- Date: 2025-12-15
-- Purpose: Track processed validation results to ensure exactly-once semantics

CREATE TABLE IF NOT EXISTS validation_requests (
    id BIGSERIAL PRIMARY KEY,
    
    -- Unique correlation ID from the validation request (ensures idempotence)
    correlation_id VARCHAR(36) NOT NULL UNIQUE,
    
    -- Reference to the transaction being validated
    transaction_id BIGINT NOT NULL,
    
    -- Status: PENDING, PROCESSED, EXPIRED
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    
    -- Timestamps
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    expires_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '5 minutes'),
    
    -- Audit
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_validation_requests_correlation_id 
    ON validation_requests(correlation_id);

CREATE INDEX IF NOT EXISTS idx_validation_requests_transaction_id 
    ON validation_requests(transaction_id);

CREATE INDEX IF NOT EXISTS idx_validation_requests_status 
    ON validation_requests(status);

CREATE INDEX IF NOT EXISTS idx_validation_requests_expires_at 
    ON validation_requests(expires_at);

-- Composite index for finding pending validations
CREATE INDEX IF NOT EXISTS idx_validation_requests_pending 
    ON validation_requests(status, expires_at) 
    WHERE status = 'PENDING';

-- Add comments for documentation
COMMENT ON TABLE validation_requests IS 
    'Tracks validation requests for idempotence. Ensures exactly-once processing of Kafka validation results.';

COMMENT ON COLUMN validation_requests.correlation_id IS 
    'Unique ID generated by transaction-service for this validation request. Used as primary key for idempotence.';

COMMENT ON COLUMN validation_requests.transaction_id IS 
    'References the transaction being validated.';

COMMENT ON COLUMN validation_requests.status IS 
    'PENDING: waiting for result, PROCESSED: result received and processed, EXPIRED: no response within 5 minutes';

COMMENT ON COLUMN validation_requests.expires_at IS 
    'Timestamp after which the validation is considered expired (default: 5 minutes). Used for cleanup.';
