spring.application.name=user-service
server.port=8082

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://192.168.0.122:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / Hibernate config
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ✅ JWT Configuration
app.jwt.secret=7pBJFFNs9RzeTwTz/NHFY1e1QyFVnDoZbBTG8zsdGHeAsAzmqcxLneWASllVgTbAdgdrS+XhAR9nfg1hPglA3Q==
app.jwt.access-expiration=100000
app.jwt.refresh-expiration=2592000000

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

spring.security.user.name=admin
spring.security.user.password=motDePasseFixe
spring.security.user.roles=USER

# Kafka Configuration
spring.kafka.bootstrap-servers=192.168.0.122:9092
spring.kafka.consumer.group-id=user-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Kafka Topics
kafka.topics.user-created=user-registered
kafka.topics.wallet-created=wallet-created-topic

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# ===============================
# Configuration des services externes
# ===============================
wallet.service.url=http://localhost:8084
# wallet.service.url=${WALLET_SERVICE_URL:http://wallet-service:8086}

# Configuration de l'URL de vérification email
app.verification.base-url=http://192.168.0.234:8082

# ===============================
# Configuration Feign - Default
# ===============================
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=10000
feign.client.config.default.loggerLevel=full

# ===============================
# Configuration Feign - wallet-service
# ===============================
feign.client.config.wallet-service.connectTimeout=3000
feign.client.config.wallet-service.readTimeout=8000
feign.client.config.wallet-service.loggerLevel=full
feign.client.config.wallet-service.errorDecoder=com.fintech.user.client.WalletServiceErrorDecoder

# ===============================
# Feign Compression
# ===============================
feign.compression.request.enabled=true
feign.compression.request.mime-types=text/xml,application/xml,application/json
feign.compression.request.min-request-size=2048
feign.compression.response.enabled=true

# ===============================
# Resilience4j - Circuit Breaker
# ===============================
resilience4j.circuitbreaker.instances.walletService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.walletService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.walletService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.walletService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.walletService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.walletService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.walletService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.walletService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.walletService.slowCallRateThreshold=100
resilience4j.circuitbreaker.instances.walletService.slowCallDurationThreshold=5s
resilience4j.circuitbreaker.instances.walletService.eventConsumerBufferSize=10

resilience4j.circuitbreaker.instances.walletService.recordExceptions[0]=feign.FeignException
resilience4j.circuitbreaker.instances.walletService.recordExceptions[1]=java.net.ConnectException
resilience4j.circuitbreaker.instances.walletService.recordExceptions[2]=java.net.SocketTimeoutException

# ===============================
# Resilience4j - Retry
# ===============================
resilience4j.retry.instances.walletService.maxAttempts=3
resilience4j.retry.instances.walletService.waitDuration=1s
resilience4j.retry.instances.walletService.exponentialBackoffMultiplier=2

resilience4j.retry.instances.walletService.retryExceptions[0]=feign.RetryableException
resilience4j.retry.instances.walletService.retryExceptions[1]=java.net.ConnectException

#resilience4j.retry.instances.walletService.ignoreExceptions[0]=com.fintech.user.exception.BusinessException

# ===============================
# Resilience4j - TimeLimiter
# ===============================
resilience4j.timelimiter.instances.walletService.timeoutDuration=10s
resilience4j.timelimiter.instances.walletService.cancelRunningFuture=true

# ===============================
# Logging
# ===============================
logging.level.com.fintech.user.client=DEBUG
logging.level.feign=DEBUG

# ===============================
# Telegram Bot Configuration
# ===============================
telegram.bot.token=7490034483:AAFCwqBCCjpaHGfLlsfz6ucymsTaU0peov4
telegram.chat.id=-1003482975630

# ===============================
# Twilio Configuration
# ===============================
# twilio.account-sid=${TWILIO_ACCOUNT_SID:AC4ee2203ca9ee74fe8df3010675a03cd2}
# twilio.auth-token=${TWILIO_AUTH_TOKEN:c94f6cac374ebe85351766659a3ced4b}
#twilio.phone-number=${TWILIO_PHONE_NUMBER:+17177897813}
