spring.application.name=wallet-transfert-service
server.port=8081

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://192.168.0.122:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=1234

## JPA / Hibernate config
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


